lane :release do
    api_key = app_store_connect_api_key(
      key_id: "D383SF739",
      issuer_id: "6053b7fe-68a8-4acb-89be-165aa6465141",
      key_filepath: "./AuthKey_D383SF739.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
  
    pilot(api_key: api_key)
  end
  