const locators = {
  checkboxWrapper: 'checkbox-wrapper',
  codeWindow: 'code-window',
  codeWindowContent: 'code-window-content',
  comingSoon: 'coming-soon',
  copyIcon: 'copy-icon',
  copyWithCheck: 'copy-with-check',
  errorModal: 'error-modal',
  errorModalClose: 'error-modal-close',
  frame: 'frame',
  hideIcon: 'hide-icon',
  mnemonicContainerShown: 'mnemonic-container-shown',
  mnemonicContainerHidden: 'mnemonic-container-hidden',
  mnemonicContainerMnemonic: 'mnemonic-container-mnemonic',
  pageBack: 'page-back',
  leftRightArrows: 'left-right-arrows-icon',
  listItem: 'list-item',
  list: 'list',
  linkActive: 'link-active',
  navButton: 'nav-button',
  navBar: 'nav-bar',
  settingsIcon: 'settings-icon',
  splashWrapper: 'splash-wrapper',
  tickIcon: 'tick-icon',
  upDownArrows: 'up-down-arrows-icon',
  vegaIcon: 'vega-icon',
  vega: 'vega',
  walletIcon: 'wallet-icon'
}

export default locators
