const locators = {
  checkboxWrapper: 'checkbox-wrapper',
  codeWindow: 'code-window',
  codeWindowContent: 'code-window-content',
  comingSoon: 'coming-soon',
  copyIcon: 'copy-icon',
  connectionModalSuccess: 'connection-modal-success',
  connectionModalApprove: 'connection-modal-approve',
  connectionModalAccessListTitle: 'connection-modal-access-list-title',
  connectionModalAccessListAccess: 'connection-modal-access-list-access',
  connectionModalDenyButton: 'connection-modal-deny-button',
  connectionModalApproveButton: 'connection-modal-approve-button',
  connectionModal: 'connection-modal',
  copyWithCheck: 'copy-with-check',
  dAppHostname: 'dapp-hostname',
  errorModal: 'error-modal',
  errorModalClose: 'error-modal-close',
  frame: 'frame',
  hideIcon: 'hide-icon',
  modalHeader: 'modal-header',
  modalHeaderTitle: 'modal-header-title',
  mnemonicContainerShown: 'mnemonic-container-shown',
  mnemonicContainerHidden: 'mnemonic-container-hidden',
  mnemonicContainerMnemonic: 'mnemonic-container-mnemonic',
  pageBack: 'page-back',
  hostImage: 'host-image',
  leftRightArrows: 'left-right-arrows-icon',
  listItem: 'list-item',
  list: 'list',
  linkActive: 'link-active',
  navButton: 'nav-button',
  navBar: 'nav-bar',
  settingsIcon: 'settings-icon',
  splashWrapper: 'splash-wrapper',
  tickIcon: 'tick-icon',
  upDownArrows: 'up-down-arrows-icon',
  vegaIcon: 'vega-icon',
  vega: 'vega',
  walletIcon: 'wallet-icon'
}

export default locators
