name: Build iOS ipa

on:
  pull_request:
  workflow_dispatch:
    inputs:
      trigger-ios-test:
        description: 'Trigger iOS Test workflow'
        required: false

env:
  BS_USER: ${{ secrets.BROWSERSTACK_USERNAME }}
  BS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  build-ios:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: yarn run build:beta

      - run: fastlane release
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          IOS_APP_STORE_CONNECT_API_KEY: ${{ secrets.IOS_APP_STORE_CONNECT_API_KEY }}
          CI_BOT_GITHUB_TOKEN: ${{ secrets.CI_BOT_GITHUB_TOKEN }}

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: app.ipa
          path: './app.ipa'

      - name: Upload iOS app to BrowserStack
        id: ios_app_upload
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api-cloud.browserstack.com/app-automate/upload
          method: POST
          username: ${{ env.BS_USER }}
          password: ${{ env.BS_KEY }}
          data: '{ "custom_id": "IOSApp" }'
          files: '{ "file": "${{ github.workspace }}/app.ipa" }'
          maskResponse: false
      - name: Show Response
        run: |
          echo ${{ steps.ios_app_upload.outputs.response }}
          echo ${{ steps.ios_app_upload.outputs.headers }}
          echo ${{ fromJson(steps.ios_app_upload.outputs.response).field_you_want_to_access }}

      - name: Dispatch iOS Test workflow
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.trigger-ios-test
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CI_BOT_GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: test_ios
