name: 'Upload app to BrowserStack'

on:
  pull_request:
  workflow_dispatch:

env:
  BS_USER: ${{ secrets.BROWSERSTACK_USERNAME }}
  BS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

jobs:
  upload-app:
    name: Upload App to BrowserStack
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Upload iOS App
        id: ios_app_upload
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api-cloud.browserstack.com/app-automate/upload
          method: POST
          username: ${{ env.BS_USER }}
          password: ${{ env.BS_KEY }}
          data: '{ "custom_id": "IOSApp" }'
          files: '{ "file": "${{ github.workspace }}/test/app.ipa" }'
