name: Build iOS ipa

on:
  push:
    branches: ['ci/build-ios']

jobs:
  generate-requests:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3

      # - name: Setup Node.js Latest
      #   uses: actions/setup-node@v3
      #   with:
      #     cache: 'yarn'
      #     node-version-file: '.nvmrc'

      # - name: Install dependencies
      #   run: yarn install
      # - name: Build app
      #   run: yarn run build:beta

      - name: Archive
        run: |
          xcodebuild -project "./ios-app/Vega Wallet/Vega Wallet.xcodeproj" \
          -scheme "Vega Wallet" \
          archive \
          -archivePath "./app.xcarchive" \
          ENABLE_HARDENED_RUNTIME=NO \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY=
      - name: Build iOS app
        run: |
          xcodebuild \
          -exportArchive \
          -exportOptionsPlist "./ios-app/ExportOptions.plist" \
          -archivePath app.xcarchive \
          -exportPath ./test.ipa
