name: Deploy sample dApp to Pages

on:
  push:
    branches: ['ci/build-ios']

jobs:
  generate-requests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: './ios-app/Vega Wallet'
          p12-base64: ${{ secrets.IOS_P12_BASE_64 }}
          mobile-provision: ${{ secrets.IOS_MOBILE_PROVISION }}
          code-signing-identity: ${{ secrets.IOS_CERTIFICATE_IDENTITY_ID }}
          team-id: ${{ secrets.IOS_TEAM_NAME }}
