name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check if Chrome is installed
        run: |
         whereis google-chrome
         whereis libgconf-2-4


      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Uninstall existing chrome
        run: |
            sudo apt-get remove google-chrome-stable
            sudo apt-get purge google-chrome-stable
            sudo apt purge chromium-browser
            whereis google-chrome

      - name: Install Chrome and Chromedriver
        run: |
            sudo apt-get update
            sudo apt-get install -y xvfb libxi6 libgconf-2-4
        
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update
            sudo apt-get install google-chrome-stable

            CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
            LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
            wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/
            sudo chown root:root /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver

      - name: Check if Chrome is installed and kill any running instances 
        run: |
         whereis chromedriver
         chromedriver --version
         google-chrome --version


      - name: Install Xvfb and wait-for-it tool
        run: |
           sudo apt-get update && sudo apt-get install -y xvfb
           wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
           chmod +x wait-for-it.sh
           sudo chmod 1777 /tmp/.X11-unix

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x16 -ac 
         
      - name: Wait for Xvfb to start
        run: |
          Xvfb :99 -screen 0 1024x768x16 -ac &
          n=0
          until [ $n -ge 5 ]
          do
            if [ -n "${DISPLAY+x}" ]; then
              break
            fi
            n=$((n+1))
            sleep 1
          done
          if [ -z "${DISPLAY+x}" ]; then
            echo "Xvfb failed to start"
            exit 1
          fi
          echo "Xvfb started successfully"
            
      - name: Start chrome
        run: google-chrome --enable-logging --v=1

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: |
          yarn
          yarn build:chrome

      - name: Run tests
        run: yarn test:e2e:chrome

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST E2E Tests
          path: ./test-reports/e2e-test-results.xml
          reporter: jest-junit
