name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if Google Chrome is installed
        run: google-chrome --version

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:chrome

      - name: Run tests
        run: yarn test:e2e:chrome

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST E2E Tests
          path: ./test-reports/e2e-test-results.xml
          reporter: jest-junit
