name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chrome-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install chrome and chromedriver
        run: |
          bash .github/scripts/install_chromedriver.sh
          bash .github/scripts/install_chrome.sh

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test-e2e
        env:
          REACT_APP_TEST: true

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            echo "$file was changed"
          done
      # - name: Evaluate if there are changes
      #   if: steps.check-changes.outputs.outcome == failure()
      #   run: |
      #     echo "There are uncommitted schema changes for AJV"
      #     exit 1

      - name: Run Chrome e2e tests
        run: yarn test:e2e:chrome:ci

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST E2E Tests - Chrome
          path: ./test/test-reports/chrome-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test screenshots chrome
          path: ./test/test-screenshots

  firefox-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test-e2e

      # If the build results in changes this points to uncommitted schema changes for AJV not being generated
      # fail the release if that is the case
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            echo "$file was changed"
          done
        with:
          files_yaml: |
            web-extension:
              - web-extension/**
            yarn:
              - yarn.lock
      # - name: Evaluate if there are changes
      #   if: steps.check-changes.outputs.outcome == failure()
      #   run: |
      #     echo "There are uncommitted schema changes for AJV"
      #     exit 1

      - name: Install dev version of firefox
        run: |
          wget "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" -O Firefox-dev.tar.bz2
          sudo tar xjf Firefox-dev.tar.bz2 -C /opt/
          rm -r Firefox-dev.tar.bz2
          sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox-dev

      - name: Run Firefox e2e tests
        run: yarn test:e2e:firefox:ci

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST E2E Tests - Firefox
          path: ./test/test-reports/firefox-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test screenshots firefox
          path: ./test/test-screenshots

  chrome-keep-alive-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install chrome and chromedriver
        run: |
          bash .github/scripts/install_chromedriver.sh
          bash .github/scripts/install_chrome.sh

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test-e2e
        env:
          REACT_APP_TEST: true

      - name: Run keep alive check using Xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:keepalive

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST Keep Alive - Chrome
          path: ./test/test-reports/chrome-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: keep alive screenshots chrome
          path: ./test/test-screenshots
