name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chrome-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test
        env:
          REACT_APP_TEST: true

      - name: Run E2E tests using Xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:e2e:chrome

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST E2E Tests - Chrome
          path: ./test/test-reports/chrome-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test screenshots chrome
          path: ./test/test-screenshots

  firefox-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:test

      - name: Install dev version of firefox
        run: |
          wget "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US" -O Firefox-dev.tar.bz2
          sudo tar xjf Firefox-dev.tar.bz2 -C /opt/
          rm -r Firefox-dev.tar.bz2
          sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox-dev

      - name: Run Firefox e2e tests
        run: yarn test:e2e:firefox:ci

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST E2E Tests - Firefox
          path: ./test/test-reports/firefox-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test screenshots firefox
          path: ./test/test-screenshots
