name: End-to-End Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  chrome-e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Install chromedriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1-3)
          LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
          wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:chrome

      - name: Run E2E tests using Xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:e2e:chrome

      - name: Test Report
        uses: phoenix-actions/test-reporting@v9
        if: always()
        with:
          name: JEST E2E Tests - Chrome
          path: ./test-reports/chrome-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

  firefox-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - uses: browser-actions/setup-geckodriver@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: geckodriver --version

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:firefox

      - name: Run Firefox e2e tests
        run: yarn test:e2e:firefox:ci

      - name: Test Report
        uses: phoenix-actions/test-reporting@v9
        if: always()
        with:
          name: JEST E2E Tests - Firefox
          path: ./test-reports/firefox-e2e-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: output test screenshots from the final state of tests
        uses: actions/upload-artifact@v3
        with:
          name: test screenshots
          path: ./test-screenshots
