name: Deploy sample dApp to Pages

on:
  push:
    branches: ['main']
  # paths:
  #   - 'examples/**'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

  # Single deploy job since we're just deploying
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
        with:
          cache: 'yarn'
          node-version-file: '.nvmrc'
        with:
          working-directory: examples/sample-react-dapp
      - name: Build app
        run: yarn build
        with:
          working-directory: examples/sample-react-dapp

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload only the sample dApp for now
          path: './examples/sample-react-dapp/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
