name: Release extension zip

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish as a GitHub release'
        required: false
        type: boolean
        default: false
      tag:
        description: 'Git Tag to build and publish'
        required: false
        type: string
        default: ''

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "releases"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  release:
    environment:
      name: github-releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm install
      - name: Build artifacts
        run: make dist
      - name: Bundle Firefox artifacts in archive
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          directory: dist/firefox
      - name: Bundle Chrome artifacts in archive
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: zip
          directory: dist/chrome
      - name: Upload to Github Releases
        if: ${{ inputs.publish || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: build/*.zip
          name: ${{ inputs.tag || github.ref_name }}
          tag_name: ${{ inputs.tag || github.ref_name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
