name: Release extension zip

on:
  push:
    branches: ['main']

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish as a GitHub release'
        required: false
        type: boolean
        default: false
      tag:
        description: 'Git Tag to build and publish'
        required: false
        type: string
        default: ''

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'releases'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  release:
    if: ${{ inputs.publish }}
    environment:
      name: github-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [beta, mainstream]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install
      - name: Build app
        run: NODE_ENV=production yarn run build:${{ matrix.config }}

      - name: Zip Chrome
        run: cd build/chrome && zip -qq -r ../vega-browserwallet-${{ matrix.config }}-chrome-${{ inputs.tag || 'latest' }}.zip .
      - name: Zip Firefox
        run: cd build/firefox && zip -qq -r ../vega-browserwallet-${{ matrix.config }}-firefox-${{ inputs.tag || 'latest' }}.zip .

      - name: Upload to Github Releases
        if: ${{ inputs.publish }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: 'build/*.zip'
          name: ${{ inputs.tag || 'Latest' }}
          tag_name: ${{ inputs.tag || 'latest' }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
