name: Release extension zip

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+'

concurrency:
  group: 'releases'
  cancel-in-progress: true

jobs:
  release:
    environment:
      name: github-releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [beta, mainstream]
    steps:
      - uses: olegtarasov/get-tag@v2.1.3
        id: tag-name
      - run: echo ${{ steps.tag-name.outputs.tag }}
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.release.tag_name }}
      # - name: Setup Node.js Latest
      #   uses: actions/setup-node@v3
      #   with:
      #     cache: 'yarn'
      #     node-version-file: '.nvmrc'

      # - name: Install dependencies
      #   run: yarn install
      # - name: Build app
      #   run: NODE_ENV=production yarn run build:${{ matrix.config }}

      # - name: Zip Chrome
      #   run: cd build/chrome && zip -qq -r ../vega-browserwallet-${{ matrix.config }}-chrome-${{ github.event.release.tag_name || 'latest' }}.zip .
      # - name: Zip Firefox
      #   run: cd build/firefox && zip -qq -r ../vega-browserwallet-${{ matrix.config }}-firefox-${{ github.event.release.tag_name || 'latest' }}.zip .

      # - name: Upload to Github Releases
      #   uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
      #   with:
      #     files: 'build/*.zip'
      #     name: ${{ github.event.release.tag_name || 'Latest' }}
      #     tag_name: ${{ github.event.release.tag_name || 'latest' }}
      #     prerelease: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
