---
name: Release

'on':
  push:
    branches:
      - develop
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish as a GitHub release'
        required: false
        type: boolean
        default: false
      tag:
        description: 'Git Tag to build and publish'
        required: false
        type: string
        default: ''

jobs:
  release-firefox:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: ['chrome', 'firefox']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18
        id: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install root dependencies
        run: yarn install --frozen-lockfile
      - name: Build tooling
        run: yarn nx run tooling:build --skip-nx-cache
      - name: Build
        run: yarn nx run wallet-web:build:${{ matrix.browser }} --skip-nx-cache

      - name: Bundle binary in archive
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: dist/libs/wallet-web-${{ matrix.browser }}
          exclusions: '*.zip'
          filename: ${{ matrix.browser }}.zip
      
      - name: Release
        if: ${{ inputs.publish || startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
        with:
          files: dist/libs/wallet-web-${{ matrix.browser }}/${{ matrix.browser }}.zip
          name: ${{ inputs.tag || github.ref_name }}
          tag_name: ${{ inputs.tag || github.ref_name }}
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.VEGA_CI_BOT_GITHUB_TOKEN }}
