name: Unit tests & build

on:
  push:
    branches:
      - develop
      - main
  pull_request:
jobs:
  setup:
    name: Setup dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: ${{ github.base_ref }}
      - name: Use Node.js 18
        id: Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Restore node_modules from cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install root dependencies
        run: yarn install --frozen-lockfile
  format:
    name: Check code format
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Check formatting
        run: yarn nx format:check
  lint:
    name: Check lint
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint affected
        run: yarn nx affected:lint --max-warnings=0
  test:
    name: Run unit tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Test affected
        run: yarn nx affected:test
  build-firefox:
    name: Build for Firefox
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Firefox build affected
        run: yarn nx affected:build --configuration=firefox
  build-chrome:
    name: Build for Chrome
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Chrome build affected
        run: yarn nx affected:build --configuration=chrome
