name: Check requests compatible with vega

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  request-generation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Generate requests
        run: yarn test:requests

      - name: Format
        run: yarn format

      - name: Test browser wallet requests compatible with vega
        run: |
          pull ghcr.io/vegaprotocol/vega/vega
          run --rm ghcr.io/vegaprotocol/vega/vega tools check-tx --txdir=../request-files
