name: iOS Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ios-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

    #Build the app locally 
    #  - name: Build
    #   run: 
        

    #Upload the build to browser stack in another action here

      - name: Run E2E tests using Xvfb
        uses: coactions/setup-xvfb@v1
        with:
          run: yarn test:ios
        env:
            BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
            BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
            #These will need to be updated to be credentials for a specific CI account!