name: Check requests compatible with vega

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  request-generation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Generate requests
        run: yarn test:requests

      - name: Format
        run: yarn format

      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        if: always()
        with:
          name: JEST Unit Tests (BE)
          path: ./test/test-reports/backend-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: Get Vega Tools
        uses: actions/checkout@v2
        with:
          repository: vegaprotocol/vega
          ref: 'test/check-transaction'

      - name: build vega
        run: |
          pwd
          ls
          cd vegawallet-browser/vega
          cd vega
          make build
          vega tools check-tx --txdir=./requestfiles
