name: Check requests compatible with vega

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  request-generation-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Generate requests
        run: yarn test:requests

      - name: Format
        run: yarn format

      - name: Get Vega Tools
        uses: actions/checkout@v2
        with:
          repository: vegaprotocol/vega
          ref: 'test/check-transaction'
          path: vega

      - name: Test browser wallet requests compatible with vega
        run: |
          cd vega
          make build
          ./cmd/vega/vega tools check-tx --txdir=../request-files
