name: Unit tests and lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      # - name: Format
      #   run: yarn format

      - name: Test
        run: yarn test:ci

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST Tests
          path: ./test-reports/unit-test-results.xml
          reporter: jest-junit
