name: Unit tests and lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ui-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      # - name: Format
      #   run: yarn format

      - name: Test
        run: yarn test:ci

      - name: Test Report
        uses: phoenix-actions/test-reporting@v9
        if: always()
        with:
          name: JEST Unit Tests (FE)
          path: ./test-reports/unit-test-results.xml
          reporter: jest-junit
          output-to: step-summary

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
  backend-unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '*'

      - name: Install dependencies
        run: yarn install

      - name: Test
        run: yarn test:backend

      - name: Test Report
        uses: phoenix-actions/test-reporting@v9
        if: always()
        with:
          name: JEST Unit Tests (BE)
          path: ./test-reports/backend-test-results.xml
          reporter: jest-junit
          output-to: step-summary
