name: 'Check Requests Compatible With Vega Envs'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  generate-requests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install

      - name: Generate requests
        run: yarn test:requests
        id: generate-requests

      - name: Archive request files
        uses: actions/upload-artifact@v2
        with:
          name: request-files
          path: request-files

  test-requests:
    needs: generate-requests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: ['mainnet', 'fairground']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js Latest
        uses: actions/setup-node@v3
        with:
          node-version: '*'
          registry-url: 'https://registry.npmjs.org'

      - name: Download request files
        uses: actions/download-artifact@v2
        with:
          name: request-files
          path: request-files

      - name: ${{ matrix.environment }}-check requests compatible
        run: |
          pwd
          ls
          envVersion=$(node ./.github/scripts/get-version.cjs ${{ matrix.environment }})
          echo "-------- ${{ matrix.environment }} is running on vega $envVersion --------"
          docker pull ghcr.io/vegaprotocol/vega/vega:$envVersion
          docker run --rm -v $(pwd)/request-files:/txdir ghcr.io/vegaprotocol/vega/vega:$envVersion tools check-tx --txdir=/txdir
